name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create zip
        run: |
          cd custom_components
          zip -r ../2n_intercom.zip 2n_intercom/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: 2n_intercom.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
